### ISSUE TITLE
Use releases

### ISSUE THREAD

**Issue by foaadnami** [markSmurphy/distributed-dig#10]
I was about to build similar tool (subset of features) for a side project but stumbled across this.

I cannot believe I am the first to star this. Amazing work. 

As first issue too, may I suggest using release feature of github ? This enables people who watch for release to get a notification email

Again, thanks for the amazing work 👍 🥇

**Comment by markSmurphy** [comment]
Great suggestion. I've just released a minor patch version to npm and tagged it as a release in Github to try it out.
